name: build and publish

on:
  push:
    branches:
      - main
    paths:
      - 'MaskEmail/**'
      - 'tests/**/*.ts'
      - .github/**
      - 'package.json'

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - name: run tests
        run: pnpm run test

  publish:
    needs: tests
    name: build and publish package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install
      - run: pnpm run build

      - run: |
          git config user.name github-actions
          git config user.email ${{ secrets.EMAIL }}

      - run: npm version patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}

      - run: git pull --rebase
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git push origin HEAD
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
